# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainNFZDuJ.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(888, 633)
        self.actionNew_Database = QAction(MainWindow)
        self.actionNew_Database.setObjectName(u"actionNew_Database")
        icon = QIcon()
        icon.addFile(u":/document/icons/Document/file-add-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew_Database.setIcon(icon)
        self.actionOpen_Database = QAction(MainWindow)
        self.actionOpen_Database.setObjectName(u"actionOpen_Database")
        icon1 = QIcon()
        icon1.addFile(u":/document/icons/Document/folder-open-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen_Database.setIcon(icon1)
        self.actionSave_Database = QAction(MainWindow)
        self.actionSave_Database.setObjectName(u"actionSave_Database")
        icon2 = QIcon()
        icon2.addFile(u":/device/icons/Device/save-2-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave_Database.setIcon(icon2)
        self.actionSave_Database_as = QAction(MainWindow)
        self.actionSave_Database_as.setObjectName(u"actionSave_Database_as")
        icon3 = QIcon()
        icon3.addFile(u":/document/icons/Document/file-copy-2-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave_Database_as.setIcon(icon3)
        self.actionSave_Exit = QAction(MainWindow)
        self.actionSave_Exit.setObjectName(u"actionSave_Exit")
        icon4 = QIcon()
        icon4.addFile(u":/system/icons/System/close-circle-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave_Exit.setIcon(icon4)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon5 = QIcon()
        icon5.addFile(u":/system/icons/System/question-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAdd_Group = QAction(MainWindow)
        self.actionAdd_Group.setObjectName(u"actionAdd_Group")
        icon6 = QIcon()
        icon6.addFile(u":/document/icons/Document/folder-add-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAdd_Group.setIcon(icon6)
        self.actionEdit_Group = QAction(MainWindow)
        self.actionEdit_Group.setObjectName(u"actionEdit_Group")
        icon7 = QIcon()
        icon7.addFile(u":/document/icons/Document/folder-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionEdit_Group.setIcon(icon7)
        self.actionDelete_Group = QAction(MainWindow)
        self.actionDelete_Group.setObjectName(u"actionDelete_Group")
        icon8 = QIcon()
        icon8.addFile(u":/document/icons/Document/folder-zip-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDelete_Group.setIcon(icon8)
        self.actionNew_Entry = QAction(MainWindow)
        self.actionNew_Entry.setObjectName(u"actionNew_Entry")
        icon9 = QIcon()
        icon9.addFile(u":/system/icons/System/add-box-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew_Entry.setIcon(icon9)
        self.actionEdit_Entry = QAction(MainWindow)
        self.actionEdit_Entry.setObjectName(u"actionEdit_Entry")
        icon10 = QIcon()
        icon10.addFile(u":/system/icons/System/checkbox-blank-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionEdit_Entry.setIcon(icon10)
        self.actionDelete_Entry = QAction(MainWindow)
        self.actionDelete_Entry.setObjectName(u"actionDelete_Entry")
        icon11 = QIcon()
        icon11.addFile(u":/system/icons/System/checkbox-indeterminate-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDelete_Entry.setIcon(icon11)
        self.actionOptions = QAction(MainWindow)
        self.actionOptions.setObjectName(u"actionOptions")
        icon12 = QIcon()
        icon12.addFile(u":/document/icons/Document/file-settings-line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOptions.setIcon(icon12)
        self.actionLight_Theme = QAction(MainWindow)
        self.actionLight_Theme.setObjectName(u"actionLight_Theme")
        self.actionDark_Theme = QAction(MainWindow)
        self.actionDark_Theme.setObjectName(u"actionDark_Theme")
        self.horizontal_table_layout = QWidget(MainWindow)
        self.horizontal_table_layout.setObjectName(u"horizontal_table_layout")
        self.horizontalLayout = QHBoxLayout(self.horizontal_table_layout)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.listWidget_groups = QListWidget(self.horizontal_table_layout)
        self.listWidget_groups.setObjectName(u"listWidget_groups")

        self.horizontalLayout.addWidget(self.listWidget_groups)

        self.tableWidget_entries = QTableWidget(self.horizontal_table_layout)
        if (self.tableWidget_entries.columnCount() < 6):
            self.tableWidget_entries.setColumnCount(6)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget_entries.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget_entries.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget_entries.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget_entries.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_entries.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_entries.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        self.tableWidget_entries.setObjectName(u"tableWidget_entries")
        self.tableWidget_entries.setSelectionMode(QAbstractItemView.SingleSelection)

        self.horizontalLayout.addWidget(self.tableWidget_entries)

        self.horizontalLayout.setStretch(1, 4)
        MainWindow.setCentralWidget(self.horizontal_table_layout)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 888, 22))
        self.menuDatabase = QMenu(self.menubar)
        self.menuDatabase.setObjectName(u"menuDatabase")
        self.menuEntry = QMenu(self.menubar)
        self.menuEntry.setObjectName(u"menuEntry")
        self.menuGroups = QMenu(self.menubar)
        self.menuGroups.setObjectName(u"menuGroups")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuTheme = QMenu(self.menuTools)
        self.menuTheme.setObjectName(u"menuTheme")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuGroups.menuAction())
        self.menubar.addAction(self.menuEntry.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuDatabase.addAction(self.actionNew_Database)
        self.menuDatabase.addAction(self.actionOpen_Database)
        self.menuDatabase.addAction(self.actionSave_Database)
        self.menuDatabase.addAction(self.actionSave_Database_as)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.actionSave_Exit)
        self.menuEntry.addAction(self.actionNew_Entry)
        self.menuEntry.addAction(self.actionEdit_Entry)
        self.menuEntry.addAction(self.actionDelete_Entry)
        self.menuGroups.addAction(self.actionAdd_Group)
        self.menuGroups.addAction(self.actionEdit_Group)
        self.menuGroups.addAction(self.actionDelete_Group)
        self.menuTools.addAction(self.menuTheme.menuAction())
        self.menuTools.addAction(self.actionOptions)
        self.menuTheme.addAction(self.actionLight_Theme)
        self.menuTheme.addAction(self.actionDark_Theme)
        self.menuHelp.addAction(self.actionAbout)
        self.toolBar.addAction(self.actionNew_Database)
        self.toolBar.addAction(self.actionOpen_Database)
        self.toolBar.addAction(self.actionSave_Database)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd_Group)
        self.toolBar.addAction(self.actionEdit_Group)
        self.toolBar.addAction(self.actionDelete_Group)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNew_Entry)
        self.toolBar.addAction(self.actionEdit_Entry)
        self.toolBar.addAction(self.actionDelete_Entry)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOptions)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Armour Password Manager", None))
        self.actionNew_Database.setText(QCoreApplication.translate("MainWindow", u"New Database", None))
        self.actionOpen_Database.setText(QCoreApplication.translate("MainWindow", u"Open Database", None))
        self.actionSave_Database.setText(QCoreApplication.translate("MainWindow", u"Save Database", None))
        self.actionSave_Database_as.setText(QCoreApplication.translate("MainWindow", u"Save Database as", None))
        self.actionSave_Exit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionAdd_Group.setText(QCoreApplication.translate("MainWindow", u"Add Group", None))
        self.actionEdit_Group.setText(QCoreApplication.translate("MainWindow", u"Edit Group", None))
        self.actionDelete_Group.setText(QCoreApplication.translate("MainWindow", u"Delete Group", None))
        self.actionNew_Entry.setText(QCoreApplication.translate("MainWindow", u"New Entry", None))
        self.actionEdit_Entry.setText(QCoreApplication.translate("MainWindow", u"Edit Entry", None))
        self.actionDelete_Entry.setText(QCoreApplication.translate("MainWindow", u"Delete Entry", None))
        self.actionOptions.setText(QCoreApplication.translate("MainWindow", u"Options", None))
        self.actionLight_Theme.setText(QCoreApplication.translate("MainWindow", u"Light Theme", None))
        self.actionDark_Theme.setText(QCoreApplication.translate("MainWindow", u"Dark Theme", None))
        ___qtablewidgetitem = self.tableWidget_entries.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Website", None));
        ___qtablewidgetitem1 = self.tableWidget_entries.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Username", None));
        ___qtablewidgetitem2 = self.tableWidget_entries.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Password", None));
        ___qtablewidgetitem3 = self.tableWidget_entries.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"URL", None));
        ___qtablewidgetitem4 = self.tableWidget_entries.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Created", None));
        ___qtablewidgetitem5 = self.tableWidget_entries.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"2FA", None));
        self.menuDatabase.setTitle(QCoreApplication.translate("MainWindow", u"Database", None))
        self.menuEntry.setTitle(QCoreApplication.translate("MainWindow", u"Entry", None))
        self.menuGroups.setTitle(QCoreApplication.translate("MainWindow", u"Groups", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuTheme.setTitle(QCoreApplication.translate("MainWindow", u"Theme", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi
